### ISSUE TITLE
Relay and scanner not connect

### ISSUE THREAD

**Issue by ghost** [readloud/PyRai#1]
When I put the relay and the scanner in the same port, the relay says :

[scanner] Scanner process started ..
[scanner] Connecting to remote relay ...
[scanner] Remote relay unreachable retrying in 5 secs ...

**Comment by readloud** [comment]
edit the file scanner.py and modify the following vars: __RELAY_H__ : The ip of the relay. __RELAY_P__ : The port of the relay.

Of course they have to match the variables of the relay.py script.
